///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePassTestSuite.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntry recording.
    /// </summary>
    [TestModule("77a1ee00-9c62-4065-a279-c558e56551b4", ModuleType.Recording, 1)]
    public partial class AddEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePassTestSuite.KeePassTestSuiteRepository repository.
        /// </summary>
        public static global::KeePassTestSuite.KeePassTestSuiteRepository repo = global::KeePassTestSuite.KeePassTestSuiteRepository.Instance;

        static AddEntry instance = new AddEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntry()
        {
            varTitle = "WordPressDemo";
            varUsername = "admin";
            varPassword = "demo123";
            varURL = "http://bitly.com/wp_demo";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntry Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsername;

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("856e3a95-1f86-49b9-b039-0bbf61df43a8")]
        public string varUsername
        {
            get { return _varUsername; }
            set { _varUsername = value; }
        }

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("0ba1ab66-b1ca-4815-b1d1-a6979a9fdc10")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        string _varURL;

        /// <summary>
        /// Gets or sets the value of variable varURL.
        /// </summary>
        [TestVariable("883af02e-b9cf-4ecd-83ed-3c5617fb8866")]
        public string varURL
        {
            get { return _varURL; }
            set { _varURL = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varIconIndex.
        /// </summary>
        [TestVariable("c48df24c-030a-4a73-997a-4632b57b8423")]
        public string varIconIndex
        {
            get { return repo.varIconIndex; }
            set { repo.varIconIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varExpires.
        /// </summary>
        [TestVariable("7230104a-3274-4758-9034-592ec4e96356")]
        public string varExpires
        {
            get { return repo.varExpires; }
            set { repo.varExpires = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("089ec43a-e859-4dd5-8fd9-1eece839e112")]
        public string varTitle
        {
            get { return repo.varTitle; }
            set { repo.varTitle = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.Edit' at Center.", repo.MainForm.EditInfo, new RecordItemIndex(0));
            repo.MainForm.Edit.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.AddEntry' at Center.", repo.KeePass.AddEntryInfo, new RecordItemIndex(1));
            repo.KeePass.AddEntry.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.Title' at Center.", repo.AddEntry.TitleInfo, new RecordItemIndex(2));
            repo.AddEntry.Title.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varTitle' with focus on 'AddEntry.Title'.", repo.AddEntry.TitleInfo, new RecordItemIndex(3));
            repo.AddEntry.Title.PressKeys(varTitle);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.MBtnIcon' at Center.", repo.AddEntry.MBtnIconInfo, new RecordItemIndex(4));
            repo.AddEntry.MBtnIcon.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'IconPicker.LI_Icon'.", repo.IconPicker.LI_IconInfo, new RecordItemIndex(5));
            repo.IconPicker.LI_Icon.Select();
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IconPicker.ButtonClose' at Center.", repo.IconPicker.ButtonCloseInfo, new RecordItemIndex(6));
            repo.IconPicker.ButtonClose.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.UserName' at Center.", repo.AddEntry.UserNameInfo, new RecordItemIndex(7));
            repo.AddEntry.UserName.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUsername' with focus on 'AddEntry.UserName'.", repo.AddEntry.UserNameInfo, new RecordItemIndex(8));
            repo.AddEntry.UserName.PressKeys(varUsername);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.Password' at Center.", repo.AddEntry.PasswordInfo, new RecordItemIndex(9));
            repo.AddEntry.Password.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'AddEntry.Password' at Center.", repo.AddEntry.PasswordInfo, new RecordItemIndex(10));
            repo.AddEntry.Password.Click(System.Windows.Forms.MouseButtons.Right, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.SelectAll' at Center.", repo.KeePass.SelectAllInfo, new RecordItemIndex(11));
            repo.KeePass.SelectAll.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPassword' with focus on 'AddEntry.Password'.", repo.AddEntry.PasswordInfo, new RecordItemIndex(12));
            repo.AddEntry.Password.PressKeys(varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.Repeat' at Center.", repo.AddEntry.RepeatInfo, new RecordItemIndex(13));
            repo.AddEntry.Repeat.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'AddEntry.Repeat' at Center.", repo.AddEntry.RepeatInfo, new RecordItemIndex(14));
            repo.AddEntry.Repeat.Click(System.Windows.Forms.MouseButtons.Right, 100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.SelectAll' at Center.", repo.KeePass.SelectAllInfo, new RecordItemIndex(15));
            repo.KeePass.SelectAll.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPassword' with focus on 'AddEntry.Repeat'.", repo.AddEntry.RepeatInfo, new RecordItemIndex(16));
            repo.AddEntry.Repeat.PressKeys(varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.URL' at Center.", repo.AddEntry.URLInfo, new RecordItemIndex(17));
            repo.AddEntry.URL.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varURL' with focus on 'AddEntry.URL'.", repo.AddEntry.URLInfo, new RecordItemIndex(18));
            repo.AddEntry.URL.PressKeys(varURL);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.MBtnStandardExpires' at Center.", repo.AddEntry.MBtnStandardExpiresInfo, new RecordItemIndex(19));
            repo.AddEntry.MBtnStandardExpires.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'KeePass.MI_Expires' at Center.", repo.KeePass.MI_ExpiresInfo, new RecordItemIndex(20));
            repo.KeePass.MI_Expires.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddEntry.ButtonOK' at Center.", repo.AddEntry.ButtonOKInfo, new RecordItemIndex(21));
            repo.AddEntry.ButtonOK.Click(100);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
